"""
Data models for the Evidex document Q&A system.

These models represent the structure of parsed research documents
and the responses generated by the system.
"""

from dataclasses import dataclass, field
from typing import Literal


@dataclass
class Paragraph:
    """A single paragraph within a document section.
    
    Attributes:
        paragraph_id: Unique identifier for this paragraph (e.g., "s1_p1")
        text: The actual text content of the paragraph
    """
    paragraph_id: str
    text: str


@dataclass
class Section:
    """A section of a document containing multiple paragraphs.
    
    Attributes:
        title: The section heading/title
        paragraphs: List of paragraphs in this section
    """
    title: str
    paragraphs: list[Paragraph] = field(default_factory=list)


@dataclass
class Document:
    """A complete document composed of sections.
    
    Attributes:
        title: The document title
        sections: List of sections in the document
    """
    title: str
    sections: list[Section] = field(default_factory=list)
    
    def get_paragraph(self, paragraph_id: str) -> Paragraph | None:
        """Retrieve a paragraph by its ID.
        
        Args:
            paragraph_id: The unique identifier of the paragraph
            
        Returns:
            The Paragraph if found, None otherwise
        """
        for section in self.sections:
            for paragraph in section.paragraphs:
                if paragraph.paragraph_id == paragraph_id:
                    return paragraph
        return None
    
    def get_paragraphs(self, paragraph_ids: list[str]) -> list[Paragraph]:
        """Retrieve multiple paragraphs by their IDs.
        
        Args:
            paragraph_ids: List of paragraph identifiers
            
        Returns:
            List of found Paragraphs (in the order requested, skipping missing)
        """
        result = []
        for pid in paragraph_ids:
            para = self.get_paragraph(pid)
            if para is not None:
                result.append(para)
        return result


@dataclass
class QAResponse:
    """Structured response from the Q&A system.
    
    Attributes:
        answer: The answer text (may be "Not defined in the paper")
        citations: List of paragraph IDs that support the answer
        confidence: Whether the system is confident in the answer
    """
    answer: str
    citations: list[str]
    confidence: Literal["high", "low"]
    
    def to_dict(self) -> dict:
        """Convert response to dictionary format."""
        return {
            "answer": self.answer,
            "citations": self.citations,
            "confidence": self.confidence,
        }
